name: JarvisLive
options:
  bundleIdPrefix: com.ablankcanvas
  developmentLanguage: en
  deploymentTarget:
    iOS: "16.0"

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift
    majorVersion: 2.0.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    majorVersion: 4.2.2
  SwiftSnapshot:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    majorVersion: 1.15.1

targets:
  JarvisLive-Sandbox:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - App/JarvisLiveApp.swift
    dependencies:
      - package: LiveKit
      - package: KeychainAccess
    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if which swiftlint >/dev/null; then
            swiftlint --config ../.swiftlint.yml
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        inputFiles:
          - $(SRCROOT)/Sources/**/*.swift
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint-output.txt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ablankcanvas.JarvisLive.Sandbox
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: ""
        INFOPLIST_FILE: JarvisLive-Sandbox/Info.plist
        DEVELOPMENT_ASSET_PATHS: "JarvisLive-Sandbox/Preview Content"
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Jarvis Live needs microphone access for voice interaction"
        INFOPLIST_KEY_NSCameraUsageDescription: "Jarvis Live needs camera access for document scanning and visual analysis"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: SANDBOX

  JarvisLive:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - App/JarvisLiveSandboxApp.swift
    dependencies:
      - package: LiveKit
      - package: KeychainAccess
    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if which swiftlint >/dev/null; then
            swiftlint --config ../.swiftlint.yml
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        inputFiles:
          - $(SRCROOT)/Sources/**/*.swift
        outputFiles:
          - $(DERIVED_FILE_DIR)/swiftlint-output.txt
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ablankcanvas.JarvisLive
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: ""
        INFOPLIST_FILE: Resources/Info.plist
        DEVELOPMENT_ASSET_PATHS: "JarvisLive-Sandbox/Preview Content"
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Jarvis Live needs microphone access for voice interaction"
        INFOPLIST_KEY_NSCameraUsageDescription: "Jarvis Live needs camera access for document scanning and visual analysis"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"

  JarvisLiveTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - JarvisLiveTests
    dependencies:
      - target: JarvisLive-Sandbox
      - package: SwiftSnapshot
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ablankcanvas.JarvisLiveTests
        SWIFT_EMIT_LOC_STRINGS: NO

  JarvisLiveUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - JarvisLiveUITests
    dependencies:
      - target: JarvisLive-Sandbox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ablankcanvas.JarvisLiveUITests
        SWIFT_EMIT_LOC_STRINGS: NO
        TEST_TARGET_NAME: JarvisLive-Sandbox
